# Generated by Django 3.1.1 on 2020-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64, null=True)),
                ('third_name', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=400)),
                ('ingredient_category', models.IntegerField(choices=[(1, 'naturalny'), (2, 'syntetyczny')])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=128)),
                ('ingredients', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
